import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sileo";
import { Special_Elite } from "next/font/google";

const specialElite = Special_Elite({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-special-elite",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={specialElite.variable}>
      <body>
        <Toaster position="bottom-right" />
        {children}
      </body>
    </html>
  );
}
